### PR TITLE
Addressed 'Variable name changes and save file' issues that also incl…

### PR DESCRIPTION
**Pull request by dkcoxie**
Addressed 'Variable name changes and save file' issues within Issue #75 checklist that also include Issue #70 and Issue #105

### CODE REVIEW

**Comment by kelly-sovacool** [comment]
Hi @dkcoxie, does this issue fully fix #70 and #105? If so, you can add the keyword "resolves" or "fixes" before the issue numbers in the description, the GitHub will close them automatically once this PR gets merged. See example here: #103

**Comment by kelly-sovacool** [comment]
Hi @dkcoxie & @sklucas, is this PR ready for review? Also, see my earlier question: https://github.com/UMSWC/curriculum/pull/114#issuecomment-773453653

**Review by sklucas — APPROVED** [review]

**Comment by kelly-sovacool** [comment]
Can @dkcoxie or @sklucas resolve the merge conflicts so we can merge this PR?

**Comment by sklucas** [comment]
I think there is still an issue of using the gapminder_data_2007 variable carried through to the end of the lesson, but for now, I've fixed the merge conflicts and can go back and take a look at it in a new issue.

**Pull request merged**
